using Metalama.Framework.Advising;
using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using Microsoft.Extensions.DependencyInjection;

namespace Metalama.Samples.Metrics;

internal class ImplementAddMetricsAspect : CompilationAspect
{
    public override void BuildAspect(IAspectBuilder<ICompilation> builder)
    {
        var type = builder.WithNamespace("AutoGenerated")
            .IntroduceClass("MetricRegistrations", buildType: t => t.IsStatic = true);
        type.IntroduceMethod(nameof(AddAutoGeneratedMetrics));
    }

    [Template]
    public static void AddAutoGeneratedMetrics(ServiceCollection serviceCollection)
    {
        foreach (var predecessor in meta.AspectInstance.Predecessors)
        {
            var targetType = (INamedType) predecessor.Instance.TargetDeclaration.GetTarget();
            serviceCollection.AddSingleton(targetType.ToType());
        }
    }
}